language: node_js
node_js:
  - 7

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t travis/image_test .
  - docker image ls
  - docker push travis/image_test
