language: node_js
node_js:
  - 7

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker login --username="$HEROKU_USERNAME" --password="$HEROKU_AUTH_TOKEN" registry.heroku.com

script:
  - docker build -t oliver79913/image_test .
  - docker image ls
  - docker push oliver79913/image_test

